#!/bin/bash

: '
    #===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===
    Filename:       pacrepoman
    Author:         Yannick Brouard
    Repository:     https://github.com/yckbrd/pacrepoman
    License:        GNU Lesser General Public License v2.1
    +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---
    Name:           pacrepoman - the pacMAN repoSITORY manAGER
    Type:           Shell script
    Version:        0.1.0.20241102
    Description:    pacrepoman manages Pacman Repositories directly from the command line. 
                    Adding, removing, enabling, disabling Pacman Repositories without the 
                    need for a text editor. And without the need for user interaction when 
                    used within a script.
    #===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===
: '

: '
    #===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===
    Changelog:
    +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---
    0.1.0.20241102      - Switched to GNU Lesser General Public License v2.1
                        - Changed versioning to Major.Minor.Patch.Build Date*-Build Number**
                        - Changed header, changelog and help style
                        - Revised header, description and help.
                        
                        *Date format YYYYMMDD
                        **Number format XX; only used if there is more than one build per date
    +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---
    0.1.0.20230520      - Initial release
    #===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===
: '

conff=/etc/pacman.conf
option=$1
name=$2
location=$3
trustlvl=$4

help_show()
{
cat <<__EOF__
    #===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===
    pacrepoman - the pacMAN repoSITORY manAGER
    
    pacrepoman manages Pacman Repositories directly from the command line. Adding, removing, 
    enabling, disabling Pacman Repositories without the need for a text editor. And without 
    the need for user interaction when used within a script.
    
    Usage:  pacrepoman [option] <name> <url OR path> <siglevel>
            
            -h --help                                   Display this help.
            
            -l --list                                   List all repositories 
                                                        in "$conff".
            
            -q --query <name>                           Query repository <name> 
                                                        in "$conff".
            
            -a --add <name> <url OR path> <siglevel>    Add repository <name> and location, 
                                                        server <url> or mirrorlist <path>, 
                                                        to "$conff". 
                                                        Specifying trust level <siglevel> 
                                                        is optional.
            
            -r --remove <name>                          Remove repository <name> 
                                                        from "$conff".
            
            -e --enable <name>                          --- NOT YET IMPLEMENTED --- 
                                                        Enable repository <name> 
                                                        in "$conff".
            
            -d --disable <name>                         --- NOT YET IMPLEMENTED --- 
                                                        Disable repository <name> 
                                                        in "$conff".
                                                        
    
                                                                                   0.1.0.20241102
    #===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===
__EOF__
}

write_permission_check()
{
if [ -w "$conff" ]
then
echo "$conff exists and write permission granted."
else
echo "$conff not found or write permission denied."
echo "Please verify path and/or execute pacrepoman with root privileges."
exit
fi
}

repo_list()
{
sed -E "/^\[|^\#\[/! d" $conff | sed "/\[options\]/ d" | sed "/\#\[custom\]/ d" | sed "s/\[//" | sed "s/\]//"
}

repo_query()
{
awk "/\\[$name\\]/,/^$/" $conff | awk "!/^$/"
}

repo_query_result="$(repo_query)"

repo_check()
{
if [ "$repo_query_result" != '' ]
then
echo "Repository '$name' already present in $conff."
exit
else
echo "Repository '$name' not found in $conff."
fi
}

repo_add()
{
echo >> $conff
echo "[$name]" >> $conff
if [ $trustlvl != '' ]
then
echo "SigLevel = $trustlvl" >> $conff
fi
if [[ $location == .* ]] || [[ $location == /* ]] || [[ $location == file://* ]]
then
echo "Include = $location" >> $conff
else
echo "Server = $location" >> $conff
fi
}

repo_add_echo()
{
repo_query
echo "...has been added to $conff"
}

repo_remove()
{
conf=$(<"$conff")
echo "${conf/"$repo_query_result"}" > $conff
echo "Repository '$name' has been removed from $conff."
}

not_yet_implemented()
{
echo "Apologies, but unfortunately this option has not been implemented yet!"
}

repo_enable()
{
not_yet_implemented
}

repo_disable()
{
not_yet_implemented
}

case $1 in

-w|--write-permission)
write_permission_check
;;

-l|--list)
repo_list
;;

-q|--query)
repo_query
;;

-c|--check)
repo_check
;;

-a|--add)
write_permission_check
repo_check
repo_add
repo_add_echo
;;

-r|--remove)
write_permission_check
repo_remove
;;

-e|--enable)
write_permission_check
repo_enable
;;

-d|--disable)
write_permission_check
repo_disable
;;

-h|--help|*)
help_show
;;

esac
